name: Python CI with Coverage & GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage-badge

      - name: Verificaci贸n de estilo de c贸digo
        run: |
          pylint src/*.py || true

      - name: Ejecutar pruebas con coverage
        run: |
          pytest --cov=src --cov-report=html --cov-report=xml

      - name: Generar badge de cobertura
        run: |
          coverage-badge -o htmlcov/coverage-badge.svg -f

      - name: Subir reporte y badge como artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  publish-coverage:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      - name: Descargar artifact de coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
